import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import Breadcrumbs from './components/Breadcrumbs';
import Footer from './components/footer/Footer';
import Header from './components/header/Header';
import { Providers } from './providers/Providers';
import './styles/styles.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" className={`${inter.variable} ${playfair.variable}`}>
      <body>
        <Providers>
          <Header />
          <div className="main-container flex flex-col px-6 md:px-8 h-full container mx-auto max-w-[1440px]">
            <Breadcrumbs />
            <main className="flex flex-1 justify-center h-full py-10 w-full">
              {children}
            </main>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
