import type { Metadata } from 'next';
import { Providers } from './providers/Providers';
import Header from './components/header/Header';
import './styles/styles.css';
import { Inter, Playfair_Display } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${playfair.variable}`}>
      <body>
        <Providers>
          <Header />
          <main className="flex flex-1 justify-center h-full px-2 sm:px-4 md:px-8">
            {children}
          </main>
          <footer>Fotnot</footer>
        </Providers>
      </body>
    </html>
  );
}
